ConnectionStrings:
  DefaultConnection: ${DB_CONNECTION_STRING:Server=sqlserver,1433;Database=Konecta_Hr;User Id=sa;Password=pa55w0rd!;TrustServerCertificate=True;}

RabbitMq:
  HostName: ${RABBITMQ_HOST:rabbitmq}
  Port: ${RABBITMQ_PORT:5672}
  UserName: ${RABBITMQ_USERNAME:guest}
  Password: ${RABBITMQ_PASSWORD:guest}
  VirtualHost: ${RABBITMQ_VHOST:/}
  Exchange: konecta.erp
  EmployeeCreatedRoutingKey: hr.employee.created
  EmployeeExitedRoutingKey: hr.employee.exited
  EmployeeResignationApprovedRoutingKey: hr.employee.resignation.approved
  EmployeeTerminatedRoutingKey: hr.employee.terminated
  FinanceCompensationProvisionedRoutingKey: finance.compensation.provisioned
  FinanceCompensationBonusesRoutingKey: finance.compensation.bonuses
  FinanceCompensationDeductionsRoutingKey: finance.compensation.deductions
  UserProvisionedQueue: hr.user-provisioned
  UserProvisionedRoutingKey: auth.user.provisioned

Consul:
  Host: ${CONSUL_HOST:http://consul-server:8500}

JwtSettings:
  Issuer: ${JWT_ISSUER:KonectaERP}
  Audience: ${JWT_AUDIENCE:KonectaERPUsers}
  JwksUri: ${AUTH_JWKS_URI:http://authentication-service:7280/.well-known/jwks.json}
  RequireHttpsMetadata: ${JWT_REQUIRE_HTTPS:false}
  CacheDurationMinutes: 30

ServiceConfig:
  ServiceName: hr-service
  Host: 0.0.0.0
  PublicHost: ${SERVICE_PUBLIC_HOST:hr-service}
  Port: 5005
  RegisterWithConsul: ${CONSUL_REGISTER:true}
  FailFast: false
